# Nociones Básicas de Estadística.

Advertencia: El acapite que se presenta a continuación no pretende ser remplazo de un riguroso libro de estadística, apenas tocaremos las nociones mínimas de esta materia, para encaminarlo al análisis utilizando la herramienta FieldBook.

## ¿Qué necesito para utilizar la herramienta FieldBook?

Recordemos los conceptos básicos.
###Población:

Es un conjunto de individuos que comparten características en común, en un determinado tiempo y espacio, y presentar características sensibles a ser observadas y/o medidas. Convencionalmente se denota como **N**.

###Muestra:

Las poblaciones por regla general suelen ser muy grandes, y por economía se recomienda extraer un subconjunto de individuos que conforman la ploblación, a esto se le denomina **Muestra**. Convencionalmente se denota como **n**.

La muestra debe ser representativa de la población y el propósito es poder hacer inferencias sobre la población.

###Variables:

La variable es el contenedor que va a recibir el dato de cada observación, y los datos deben pertenecer a la misma característica, propiedad o atributo.

LA variables pueden ser de diferentes maneras

###Diseño experimental

DCA
DBCA
CL
F_DCA
F_DBCA

Repeticiones

obervaciones

evaluaciones

variables.

parametros


Aqui podrás  construir tu libro de campo, es decir, diseñar y exportar el único formato que  entiende la computadora para su posterior análisis.

## Importdata

Una vez recogido los datos en el formato antes exportados, ahora aquí los cargaremos en la plataforma *FieldBook* y podrás usar la herramienta filtro para elegir los factores de interés.

## Outliers

Seguidamente, podrás  dar una vista rápida a la distribución y simetria de tus datos mediante la construcción de diagramas de cajas o boxplot.

## Multivariante

Aqui se presentan pruebas de correlación, analisis de componentes principales y correlación de pearson.

## Regression

Se contruyen modelos de regresión lineal, visualización de la ecuación y representación gráfica.

## Stadistics

Se desarrollan el análisis de varianza y prueba de comparación de medias mostrada en cuadro resúmen sensible a ser exportadas.

## Graphics

La visualización de los resultados en gráfico de barras o líneas en b/n y colores. 
